version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.5-stretch
    steps:
      - checkout
      - run: ls
      - run: python -m venv env
      - run: env/bin/pip install -r requirements.txt
      - run: env/bin/python -m mypy --check-untyped-defs --ignore-missing-imports site2graph
      - run: env/bin/python -m flake8 --select F site2graph
      - run: env/bin/isort  -sp .isort.cfg  --check site2graph/*.py
      - run: env/bin/black --check site2graph/*.py
      - run: env/bin/python -m unittest discover site2graph -p "*.py"
